### PR TITLE
Ssl redirect fixed

### LINKED ISSUE #225: frontend with no default backend
### Cookbook version
latest

### Chef-client version
12.x

### Platform Details
Latest amazon linux

### Scenario:
frontend with no default backend

in a case where ssl forwarding is needed, a `default_backend` should not be required no?

ie: 

```
frontend http-in
  bind *:80
  maxconn 50000
  redirect scheme https code 301 if !{ ssl_fc }
```

### PR DESCRIPTION
**Pull request by rshade**
### Description

this is a test and fix for #225 

### Issues Resolved
#225 

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/haproxy/227)

### CODE REVIEW

**Comment by teknofire** [comment]
Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/integration/config_1/example_spec.rb, line 27 at r1](https://reviewable.io:443/reviews/sous-chefs/haproxy/227#-KlV3wwiXphsNcSZlIX7:-KlV3wwiXphsNcSZlIX8:b-sej5ke) ([raw file](https://github.com/sous-chefs/haproxy/blob/1dacbc8a669c39305776cf95504c0e7d250c1aef/test/integration/config_1/example_spec.rb#L27)):*
> ```Ruby
>   its('content') { should match(/bind 0.0.0.0:8081/) }
>   its('content') { should match(/bind 0.0.0.0:8180/) }
>   its('content') { should match(/backend servers/) }
> ```

This will match the same line as the next line for `match(/default_backend servers/)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sous-chefs/haproxy/227)*

File: test/integration/config_1/example_spec.rb [hunk 1]
```diff
@@ -25,6 +25,7 @@
   its('content') { should match(/bind 0.0.0.0:8081/) }
   its('content') { should match(/bind 0.0.0.0:8180/) }
   its('content') { should match(/backend servers/) }
+  its('content') { should match(/default_backend servers/) }
```
Comment (teknofire) [inline test/integration/config_1/example_spec.rb]: These two tests are redundant.  Both of them will match on the same line in the config, I think the second one that matches against the full `default_backend servers` line would be better.

Comment (rshade) [inline test/integration/config_1/example_spec.rb]: It should check for both though that the top level item `backend` is there, and that a default backend is set. I just have to figure out how.
